// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMI9wlsR64SDvL2P-Xj4jfnis2k9ND6z4',
    appId: '1:648971955822:web:a0f31ff0524b2df204007f',
    messagingSenderId: '648971955822',
    projectId: 'wasel-73fed',
    authDomain: 'wasel-73fed.firebaseapp.com',
    storageBucket: 'wasel-73fed.firebasestorage.app',
    measurementId: 'G-ZMKGK2XT0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmKKqAqwJjEc68Sd17OfAk181IjDP5ds',
    appId: '1:648971955822:android:fa3e320d277e8a2804007f',
    messagingSenderId: '648971955822',
    projectId: 'wasel-73fed',
    storageBucket: 'wasel-73fed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsoZTobw4FzcuEsmUljd4TTHLCYKVYOT8',
    appId: '1:648971955822:ios:5d1334f85183be1404007f',
    messagingSenderId: '648971955822',
    projectId: 'wasel-73fed',
    storageBucket: 'wasel-73fed.firebasestorage.app',
    iosBundleId: 'com.example.wasel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsoZTobw4FzcuEsmUljd4TTHLCYKVYOT8',
    appId: '1:648971955822:ios:5d1334f85183be1404007f',
    messagingSenderId: '648971955822',
    projectId: 'wasel-73fed',
    storageBucket: 'wasel-73fed.firebasestorage.app',
    iosBundleId: 'com.example.wasel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMI9wlsR64SDvL2P-Xj4jfnis2k9ND6z4',
    appId: '1:648971955822:web:315cd4daec4eb13d04007f',
    messagingSenderId: '648971955822',
    projectId: 'wasel-73fed',
    authDomain: 'wasel-73fed.firebaseapp.com',
    storageBucket: 'wasel-73fed.firebasestorage.app',
    measurementId: 'G-8WXPY8VRX5',
  );
}
